### PR TITLE
CLIENT-6455 | Added de1-ix to regions.ts

### PR DESCRIPTION
**Pull request by mhuynh5757**
**Contributing to Twilio**

> All third party contributors acknowledge that any contributions they provide will be made under the same open source license that the open source project is provided under.

- [✔️] I acknowledge that all my contributions will be made under the project's license.

### JIRA link(s):

- [CLIENT-6455](https://issues.corp.twilio.com/browse/CLIENT-6455)

### Description

Adds support for the region `de1-ix`.

### Before review
* [✔️] Updated CHANGELOG.md if necessary
* [✔️] Added unit tests if necessary
* [✔️] Updated affected documentation
* [✔️] Verified locally with `npm run build:release`
* [✔️] Manually sanity tested running locally
* [✔️] Ready for review

### Before merge
* [ ] Got one or more +1s
* [ ] Squashed erroneous commits if necessary
* [ ] Re-tested if necessary

### CODE REVIEW

**Comment by kbagchiGWC** [comment]
@mhuynh5757 curious have done any testing using `de1-ix` region? Do you have to be connected to `vpn` to be able to use the `tnx` regions? I have a similar task for voice android and trying to gather information on testing.

**Comment by ryan-rowland** [comment]
@mhuynh5757 Looks good. Are we sure we don't need to add the Tnx variant as well? All of our other ix entries have a tnx variant. Not sure what the difference is tbh.

Also, we might need to move over the travis.yml change from 1.8 to master, looks like travis build is breaking.

**Comment by ryan-rowland** [comment]
Just confirmed with Aymen and it looks like it's just `ix`. Sorry for the confusion :)

**Comment by charliesantos** [comment]
I think this looks good. Per our conversation at sprint planning, QE will help testing this. Also for future PRs, please name them using this format 😄 `CLIENT-0000 | My Awesome PR`

**Pull request merged**
